jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://124.222.162.13:3306/sharehub?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
jdbc.username=root
jdbc.password=123wspsg


dbcp2.initialSize=5
dbcp2.maxTotal=20
dbcp2.maxIdle=10
dbcp2.minIdle=5
dbcp2.maxWaitMillis=30000